---
- name: Install Bash LSP
  ansible.builtin.command: snap install bash-language-server --classic
  register: bash_lsp_install
  changed_when: bash_lsp_install.rc != 0
  failed_when: bash_lsp_install.rc != 0

- name: Install Marksman LSP
  ansible.builtin.command: snap install marksman
  register: marksman_install
  changed_when: marksman_install.rc != 0
  failed_when: marksman_install.rc != 0
